-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMlauLGqnSfPr4Lnf
N4X4KyC5YsLZgT2xWFS/cqf4PvSgCgYIKoZIzj0DAQehRANCAAR0gsX/NTdzMKL+
zflpUX8nGBM3ZBXdON3VlXz3Q5toxQ8AncJ4OxKunzGbvBt0eOxLZLF9gj45zppq
KClElv//
-----END PRIVATE KEY-----